{
 "title": "Inference",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Inf latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 23, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    },
    {
     "expr": "sum(inference_actor_to_data_store_inf_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    },
    {
     "expr": "sum(data_store_loop_to_pulsar_broker_get_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    },
    {
     "expr": "sum(pulsar_loop_to_inf_loop_end_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    },
    {
     "expr": "sum(inf_loop_to_bridge_inference_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    },
    {
     "expr": "sum(bridge_to_inf_loop_inf_result_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    },
    {
     "expr": "sum(data_store_to_grpc_inference_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    }
   ]
  },
  {
   "title": "Average",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(grpc_inference_latency_sum[1m]) /rate(grpc_inference_latency_count[1m])) / count(grpc_inference_latency_count)"
    },
    {
     "expr": "sum(rate(inference_actor_to_data_store_inf_latency_sum[1m]) /rate(inference_actor_to_data_store_inf_latency_count[1m])) / count(inference_actor_to_data_store_inf_latency_count)"
    },
    {
     "expr": "sum(rate(data_store_loop_to_pulsar_broker_get_latency_sum[1m]) /rate(data_store_loop_to_pulsar_broker_get_latency_count[1m])) / count(data_store_loop_to_pulsar_broker_get_latency_count)"
    },
    {
     "expr": "sum(rate(pulsar_loop_to_inf_loop_end_latency_sum[1m]) /rate(pulsar_loop_to_inf_loop_end_latency_count[1m])) / count(pulsar_loop_to_inf_loop_end_latency_count)"
    },
    {
     "expr": "sum(rate(inf_loop_to_bridge_inference_latency_sum[1m]) /rate(inf_loop_to_bridge_inference_latency_count[1m])) / count(inf_loop_to_bridge_inference_latency_count)"
    },
    {
     "expr": "sum(rate(bridge_to_inf_loop_inf_result_latency_sum[1m]) /rate(bridge_to_inf_loop_inf_result_latency_count[1m])) / count(bridge_to_inf_loop_inf_result_latency_count)"
    },
    {
     "expr": "sum(rate(data_store_to_grpc_inference_latency_sum[1m]) /rate(data_store_to_grpc_inference_latency_count[1m])) / count(data_store_to_grpc_inference_latency_count)"
    }
   ]
  },
  {
   "title": "ㅇㅇ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "rate(grpc_inference_latency_sum[1m]) /rate(grpc_inference_latency_count[1m])"
    }
   ]
  },
  {
   "title": "inf actor to data store ",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(inference_actor_to_data_store_inf_latency_sum[1m]) /rate(inference_actor_to_data_store_inf_latency_count[1m])"
    }
   ]
  },
  {
   "title": "data to pulsar",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 29 },
   "targets": [
    {
     "expr": "rate(data_store_loop_to_pulsar_broker_get_latency_sum[1m]) /rate(data_store_loop_to_pulsar_broker_get_latency_count[1m])"
    }
   ]
  },
  {
   "title": "pulsar to inf ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "rate(pulsar_loop_to_inf_loop_end_latency_sum[1m]) /rate(pulsar_loop_to_inf_loop_end_latency_count[1m])"
    }
   ]
  },
  {
   "title": "inf to bridge",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 41 },
   "targets": [
    {
     "expr": "rate(inf_loop_to_bridge_inference_latency_sum[1m]) /rate(inf_loop_to_bridge_inference_latency_count[1m])"
    }
   ]
  },
  {
   "title": "bridge to inf",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(bridge_to_inf_loop_inf_result_latency_sum[1m]) /rate(bridge_to_inf_loop_inf_result_latency_count[1m])"
    }
   ]
  },
  {
   "title": "data to grpc",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 55 },
   "targets": [
    {
     "expr": "rate(data_store_to_grpc_inference_latency_sum[1m]) /rate(data_store_to_grpc_inference_latency_count[1m])"
    }
   ]
  },
  {
   "title": "Inf Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\",le=\"1.0\"})"
    },
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\",le=\"5.0\"})"
    },
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\",le=\"10.0\"})"
    },
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\",le=\"20.0\"})"
    },
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\",le=\"100.0\"})"
    },
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\",le=\"+Inf\"})"
    }
   ]
  },
  {
   "title": "inf to data",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum(inference_actor_to_data_store_inf_latency_bucket{service=\"inference\",le=\"+Inf\"})"
    },
    {
     "expr": "sum(inference_actor_to_data_store_inf_latency_bucket{service=\"inference\",le=\"100.0\"})"
    },
    {
     "expr": "sum(inference_actor_to_data_store_inf_latency_bucket{service=\"inference\",le=\"10.0\"})"
    },
    {
     "expr": "sum(inference_actor_to_data_store_inf_latency_bucket{service=\"inference\",le=\"5.0\"})"
    },
    {
     "expr": "sum(inference_actor_to_data_store_inf_latency_bucket{service=\"inference\",le=\"1.0\"})"
    }
   ]
  },
  {
   "title": "data to pulsar",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(data_store_loop_to_pulsar_broker_get_latency_bucket{service=\"inference\",le=\"+Inf\"})"
    },
    {
     "expr": "sum(data_store_loop_to_pulsar_broker_get_latency_bucket{service=\"inference\",le=\"100.0\"})"
    },
    {
     "expr": "sum(data_store_loop_to_pulsar_broker_get_latency_bucket{service=\"inference\",le=\"10.0\"})"
    },
    {
     "expr": "sum(data_store_loop_to_pulsar_broker_get_latency_bucket{service=\"inference\",le=\"5.0\"})"
    },
    {
     "expr": "sum(data_store_loop_to_pulsar_broker_get_latency_bucket{service=\"inference\",le=\"1.0\"})"
    }
   ]
  },
  {
   "title": "pulsar to inf ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "sum(pulsar_loop_to_inf_loop_end_latency_bucket{service=\"inference\",le=\"+Inf\"})"
    },
    {
     "expr": "sum(pulsar_loop_to_inf_loop_end_latency_bucket{service=\"inference\",le=\"100.0\"})"
    },
    {
     "expr": "sum(pulsar_loop_to_inf_loop_end_latency_bucket{service=\"inference\",le=\"20.0\"})"
    },
    {
     "expr": "sum(pulsar_loop_to_inf_loop_end_latency_bucket{service=\"inference\",le=\"10.0\"})"
    },
    {
     "expr": "sum(pulsar_loop_to_inf_loop_end_latency_bucket{service=\"inference\",le=\"5.0\"})"
    },
    {
     "expr": "sum(pulsar_loop_to_inf_loop_end_latency_bucket{service=\"inference\",le=\"1.0\"})"
    }
   ]
  },
  {
   "title": "inf to bridge",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "sum(inf_loop_to_bridge_inference_latency_bucket{service=\"inference\",le=\"+Inf\"})"
    },
    {
     "expr": "sum(inf_loop_to_bridge_inference_latency_bucket{service=\"inference\",le=\"100.0\"})"
    },
    {
     "expr": "sum(inf_loop_to_bridge_inference_latency_bucket{service=\"inference\",le=\"20.0\"})"
    },
    {
     "expr": "sum(inf_loop_to_bridge_inference_latency_bucket{service=\"inference\",le=\"10.0\"})"
    },
    {
     "expr": "sum(inf_loop_to_bridge_inference_latency_bucket{service=\"inference\",le=\"5.0\"})"
    },
    {
     "expr": "sum(inf_loop_to_bridge_inference_latency_bucket{service=\"inference\",le=\"1.0\"})"
    }
   ]
  },
  {
   "title": "bridge to inf",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "sum(bridge_to_inf_loop_inf_result_latency_bucket{service=\"inference\",le=\"+Inf\"})"
    },
    {
     "expr": "sum(bridge_to_inf_loop_inf_result_latency_bucket{service=\"inference\",le=\"100.0\"})"
    },
    {
     "expr": "sum(bridge_to_inf_loop_inf_result_latency_bucket{service=\"inference\",le=\"20.0\"})"
    },
    {
     "expr": "sum(bridge_to_inf_loop_inf_result_latency_bucket{service=\"inference\",le=\"10.0\"})"
    },
    {
     "expr": "sum(bridge_to_inf_loop_inf_result_latency_bucket{service=\"inference\",le=\"5.0\"})"
    },
    {
     "expr": "sum(bridge_to_inf_loop_inf_result_latency_bucket{service=\"inference\",le=\"1.0\"})"
    }
   ]
  },
  {
   "title": "data to grpc",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "sum(data_store_to_grpc_inference_latency_bucket{service=\"inference\",le=\"+Inf\"})"
    },
    {
     "expr": "sum(data_store_to_grpc_inference_latency_bucket{service=\"inference\",le=\"100.0\"})"
    },
    {
     "expr": "sum(data_store_to_grpc_inference_latency_bucket{service=\"inference\",le=\"20.0\"})"
    },
    {
     "expr": "sum(data_store_to_grpc_inference_latency_bucket{service=\"inference\",le=\"10.0\"})"
    },
    {
     "expr": "sum(data_store_to_grpc_inference_latency_bucket{service=\"inference\",le=\"5.0\"})"
    },
    {
     "expr": "sum(data_store_to_grpc_inference_latency_bucket{service=\"inference\",le=\"1.0\"})"
    }
   ]
  }
 ]
}